instr = [
	('00', 'NOP'),
	('01', 'LD bc,**'),
	('02', 'LD (bc),a'),
	('03', 'INC bc'),
	('04', 'INC b'),
	('05', 'DEC b'),
	('06', 'LD b,*'),
	('07', 'RLCA'),
	('08', 'LD (**),SP'),
	('09', 'ADD hl,bc'),
	('0A', 'LD a,(bc)'),
	('0B', 'DEC bc'),
	('0C', 'INC c'),
	('0D', 'DEC c'),
	('0E', 'LD c,*'),
	('0F', 'RRCA'),
	('10', 'STOP'),
	('11', 'LD de,**'),
	('12', 'LD (de),a'),
	('13', 'INC de'),
	('14', 'INC d'),
	('15', 'DEC d'),
	('16', 'LD d,*'),
	('17', 'RLA'),
	('18', 'JR *'),
	('19', 'ADD hl,de'),
	('1A', 'LD a,(de)'),
	('1B', 'DEC de'),
	('1C', 'INC e'),
	('1D', 'DEC e'),
	('1E', 'LD e,*'),
	('1F', 'RRA'),
	('20', 'JR nz,*'),
	('21', 'LD hl, **'),
	('22', 'LDI (hl),a'),
	('23', 'INC hl'),
	('24', 'INC h'),
	('25', 'DEC h'),
	('26', 'LD h,*'),
	('27', 'DAA'),
	('28', 'JR z,*'),
	('29', 'ADD hl,hl'),
	('2A', 'LDI a,(hl)'),
	('2B', 'DEC hl'),
	('2C', 'INC l'),
	('2D', 'DEC l'),
	('2E', 'LD l,*'),
	('2F', 'CPL'),
	('30', 'JR nc,*'),
	('31', 'LD sp, **'),
	('32', 'LD (hl-),a'),
	('33', 'INC sp'),
	('34', 'INC (hl)'),
	('35', 'DEC (hl)'),
	('36', 'LD (hl),*'),
	('37', 'SCF'),
	('38', 'JR c,*'),
	('39', 'ADD hl,sp'),
	('3A', 'LDD a,(hl)'),
	('3B', 'DEC sp'),
	('3C', 'INC a'),
	('3D', 'DEC a'),
	('3E', 'LD a,*'),
	('3F', 'CCF'),
	('40', 'LD b,b'),
	('41', 'LD b,c'),
	('42', 'LD b,d'),
	('43', 'LD b,e'),
	('44', 'LD b,h'),
	('45', 'LD b,l'),
	('46', 'LD b,(hl)'),
	('47', 'LD b,a'),
	('48', 'LD c,b'),
	('49', 'LD c,c'),
	('4A', 'LD c,d'),
	('4B', 'LD c,e'),
	('4C', 'LD c,h'),
	('4D', 'LD c,l'),
	('4E', 'LD c,(hl)'),
	('4F', 'LD c,a'),
	('50', 'LD d,b'),
	('51', 'LD d,c'),
	('52', 'LD d,d'),
	('53', 'LD d,e'),
	('54', 'LD d,h'),
	('55', 'LD d,l'),
	('56', 'LD d,(hl)'),
	('57', 'LD d,a'),
	('58', 'LD e,b'),
	('59', 'LD e,c'),
	('5A', 'LD e,d'),
	('5B', 'LD e,e'),
	('5C', 'LD e,h'),
	('5D', 'LD e,l'),
	('5E', 'LD e,(hl)'),
	('5F', 'LD e,a'),
	('60', 'LD h,b'),
	('61', 'LD h,c'),
	('62', 'LD h,d'),
	('63', 'LD h,e'),
	('64', 'LD h,h'),
	('65', 'LD h,l'),
	('66', 'LD h,(hl)'),
	('67', 'LD h,a'),
	('68', 'LD l,b'),
	('69', 'LD l,c'),
	('6A', 'LD l,d'),
	('6B', 'LD l,e'),
	('6C', 'LD l,h'),
	('6D', 'LD l,l'),
	('6E', 'LD l,(hl)'),
	('6F', 'LD l,a'),
	('70', 'LD (hl),b'),
	('71', 'LD (hl),c'),
	('72', 'LD (hl),d'),
	('73', 'LD (hl),e'),
	('74', 'LD (hl),h'),
	('75', 'LD (hl),l'),
	('76', 'HALT'),
	('77', 'LD (hl),a'),
	('78', 'LD a,b'),
	('79', 'LD a,c'),
	('7A', 'LD a,d'),
	('7B', 'LD a,e'),
	('7C', 'LD a,h'),
	('7D', 'LD a,l'),
	('7E', 'LD a,(hl)'),
	('7F', 'LD a,a'),
	('80', 'ADD a,b'),
	('81', 'ADD a,c'),
	('82', 'ADD a,d'),
	('83', 'ADD a,e'),
	('84', 'ADD a,h'),
	('85', 'ADD a,l'),
	('86', 'ADD a,(hl)'),
	('87', 'ADD a,a'),
	('88', 'ADC a,b'),
	('89', 'ADC a,c'),
	('8A', 'ADC a,d'),
	('8B', 'ADC a,e'),
	('8C', 'ADC a,h'),
	('8D', 'ADC a,l'),
	('8E', 'ADC a,(hl)'),
	('8F', 'ADC a,a'),
	('90', 'SUB b'),
	('91', 'SUB c'),
	('92', 'SUB d'),
	('93', 'SUB e'),
	('94', 'SUB h'),
	('95', 'SUB l'),
	('96', 'SUB (hl)'),
	('97', 'SUB a'),
	('98', 'SBC a,b'),
	('99', 'SBC a,c'),
	('9A', 'SBC a,d'),
	('9B', 'SBC a,e'),
	('9C', 'SBC a,h'),
	('9D', 'SBC a,l'),
	('9E', 'SBC a,(hl)'),
	('9F', 'SBC a,a'),
	('A0', 'AND b'),
	('A1', 'AND c'),
	('A2', 'AND d'),
	('A3', 'AND e'),
	('A4', 'AND h'),
	('A5', 'AND l'),
	('A6', 'AND (hl)'),
	('A7', 'AND a'),
	('A8', 'XOR b'),
	('A9', 'XOR c'),
	('AA', 'XOR d'),
	('AB', 'XOR e'),
	('AC', 'XOR h'),
	('AD', 'XOR l'),
	('AE', 'XOR (hl)'),
	('AF', 'XOR a'),
	('B0', 'OR b'),
	('B1', 'OR c'),
	('B2', 'OR d'),
	('B3', 'OR e'),
	('B4', 'OR h'),
	('B5', 'OR l'),
	('B6', 'OR (hl)'),
	('B7', 'OR a'),
	('B8', 'CP b'),
	('B9', 'CP c'),
	('BA', 'CP d'),
	('BB', 'CP e'),
	('BC', 'CP h'),
	('BD', 'CP l'),
	('BE', 'CP (hl)'),
	('BF', 'CP a'),
	('C0', 'RET nz'),
	('C1', 'POP bc'),
	('C2', 'JP nz,**'),
	('C3', 'JP **'),
	('C4', 'CALL nz,**'),
	('C5', 'PUSH bc'),
	('C6', 'ADD a,*'),
	('C7', 'RST 00h'),
	('C8', 'RET z'),
	('C9', 'RET'),
	('CA', 'JP z,**'),
	('CB', 'Prefix for bit level instructions'),
	('CC', 'CALL z,**'),
	('CD', 'CALL **'),
	('CE', 'ADC a,*'),
	('CF', 'RST 08h'),
	('D0', 'RET nc'),
	('D1', 'POP de'),
	('D2', 'JP nc,**'),
	('D3', 'UNUSED'),
	('D4', 'CALL nc,**'),
	('D5', 'PUSH de'),
	('D6', 'SUB *'),
	('D7', 'RST 10h'),
	('D8', 'RET c'),
	('D9', 'RETI'),
	('DA', 'JP c,**'),
	('DB', 'UNUSED'),
	('DC', 'CALL c,**'),
	('DD', 'UNUSED'),
	('DE', 'SBC a,*'),
	('DF', 'RST 18h'),
	('E0', 'LD (FF00+*),a'),
	('E1', 'POP hl'),
	('E2', 'LD (FF00+c),a'),
	('E3', 'UNUSED'),
	('E4', 'UNUSED'),
	('E5', 'PUSH hl'),
	('E6', 'AND *'),
	('E7', 'RST 20h'),
	('E8', 'ADD SP,*'),
	('E9', 'JP (hl)'),
	('EA', 'LD (**),a'),
	('EB', 'UNUSED'),
	('EC', 'UNUSED'),
	('ED', 'UNUSED'),
	('EE', 'XOR *'),
	('EF', 'RST 28h'),
	('F0', 'LD a,(FF00+*)'),
	('F1', 'POP af'),
	('F2', 'LD a,(FF00+c)'),
	('F3', 'DI'),
	('F4', 'UNUSED'),
	('F5', 'PUSH af'),
	('F6', 'OR *'),
	('F7', 'RST 30h'),
	('F8', 'LD hl,sp+*'),
	('F9', 'LD sp,hl'),
	('FA', 'LD a,(**)'),
	('FB', 'EI'),
	('FC', 'UNUSED'),
	('FD', 'UNUSED'),
	('FE', 'CP *'),
	('FF', 'RST 38h')
]